// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_fondmontre;
lv_obj_t * ui_hourlabel;
lv_obj_t * ui_daylabel;
lv_obj_t * ui_templabel;
lv_obj_t * ui_humlabel;
lv_obj_t * ui_humlogo;
lv_obj_t * ui_Minlabel;
lv_obj_t * ui_twopoint;
lv_obj_t * ui_templogo;
lv_obj_t * ui_monthlabel;
lv_obj_t * ui_yearlabel;
lv_obj_t * ui_slash;
lv_obj_t * ui_slash1;
void ui_event_Nextbutton(lv_event_t * e);
lv_obj_t * ui_Nextbutton;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_fondmontre1;
lv_obj_t * ui_twopoint1;
lv_obj_t * ui_Minlabel1;
lv_obj_t * ui_Chronolabel;
void ui_event_nextbutton1(lv_event_t * e);
lv_obj_t * ui_nextbutton1;
void ui_event_stopbutton(lv_event_t * e);
lv_obj_t * ui_stopbutton;
lv_obj_t * ui_Seclabel;
lv_obj_t * ui_startbutton;
lv_obj_t * ui_razbutton;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_fondmontre2;
lv_obj_t * ui_magnlabel;
lv_obj_t * ui_speedlabel;
lv_obj_t * ui_speedlogo;
void ui_event_nextbutton2(lv_event_t * e);
lv_obj_t * ui_nextbutton2;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Nextbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_nextbutton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_stopbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_stopbutton, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_nextbutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
