// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#ifndef _INTERFACE_MONTRE_UI_H
#define _INTERFACE_MONTRE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void update_display_hts221(double temperature, double humidity);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_fondmontre;
extern lv_obj_t * ui_hourlabel;
extern lv_obj_t * ui_daylabel;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_humlabel;
extern lv_obj_t * ui_humlogo;
extern lv_obj_t * ui_Minlabel;
extern lv_obj_t * ui_twopoint;
extern lv_obj_t * ui_templogo;
extern lv_obj_t * ui_monthlabel;
extern lv_obj_t * ui_yearlabel;
extern lv_obj_t * ui_slash;
extern lv_obj_t * ui_slash1;
void ui_event_Nextbutton(lv_event_t * e);
extern lv_obj_t * ui_Nextbutton;
// CUSTOM VARIABLES
// ui.h
extern int ss;
extern int mm;
extern int etat;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_fondmontre1;
extern lv_obj_t * ui_twopoint1;
extern lv_obj_t * ui_Minlabel1;
extern lv_obj_t * ui_Chronolabel;
void ui_event_nextbutton1(lv_event_t * e);
extern lv_obj_t * ui_nextbutton1;
void ui_event_stopbutton(lv_event_t * e);
void ui_event_startbutton(lv_event_t * e);
void ui_event_razbutton(lv_event_t * e);
extern lv_obj_t * ui_stopbutton;
extern lv_obj_t * ui_Seclabel;
extern lv_obj_t * ui_startbutton;
extern lv_obj_t * ui_razbutton;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_fondmontre2;
extern lv_obj_t * ui_speedlogo;
void ui_event_nextbutton2(lv_event_t * e);
extern lv_obj_t * ui_nextbutton2;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_humidite_png);    // assets/humidite.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_887419821);    // assets/barre-oblique-de-division(1).png
LV_IMG_DECLARE(ui_img_1976085116);    // assets/fleche-droite.png
LV_IMG_DECLARE(ui_img_allumer_png);    // assets/allumer.png
LV_IMG_DECLARE(ui_img_1869196203);    // assets/allumer(1).png
LV_IMG_DECLARE(ui_img_poubelle_png);    // assets/poubelle.png
LV_IMG_DECLARE(ui_img_426965798);    // assets/compteur-de-vitesse.png
LV_IMG_DECLARE(ui_img_boussole_png);    // assets/boussole.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
