// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "../ui.h"

void ui_comp_screenbase_create_hook(lv_obj_t * comp)
{
}
