// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "../ui.h"

// COMPONENT screenbase

lv_obj_t * ui_screenbase_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_screenbase;
    cui_screenbase = lv_label_create(comp_parent);
    lv_obj_set_width(cui_screenbase, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(cui_screenbase, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_screenbase, -3);
    lv_obj_set_y(cui_screenbase, 77);
    lv_obj_set_align(cui_screenbase, LV_ALIGN_CENTER);
    lv_label_set_text(cui_screenbase, "Date");
    lv_obj_set_style_text_color(cui_screenbase, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_screenbase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_screenbase, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SCREENBASE_NUM);
    children[UI_COMP_SCREENBASE_SCREENBASE] = cui_screenbase;
    lv_obj_add_event_cb(cui_screenbase, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_screenbase, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_screenbase_create_hook(cui_screenbase);
    return cui_screenbase;
}

