// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#ifndef _UI_COMP_SCREENBASE_H
#define _UI_COMP_SCREENBASE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT screenbase
#define UI_COMP_SCREENBASE_SCREENBASE 0
#define _UI_COMP_SCREENBASE_NUM 1
lv_obj_t * ui_screenbase_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
