// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "../ui.h"
extern lv_obj_t *ui_magnlabel;
extern lv_obj_t *ui_speedlabel;

void update_display_magn(double magn) {
    // Mise à jour de la température
    char magntext[20];
    sprintf(magntext, "%.1f°N", magn);  // Affichage avec une décimale
    lv_label_set_text(ui_magnlabel, magntext);
    lv_obj_invalidate(ui_magnlabel);  // Actualiser l'objet de la température
    // Rafraîchir l'écran si nécessaire
    lv_refr_now(NULL);  // Rafraîchissement complet (optionnel)
}
void update_display_accel(double accel1) {
    char accel1text[20];
    sprintf(accel1text, "%.1fkm/h", accel1);  // Affichage avec une décimale
    lv_label_set_text(ui_speedlabel, accel1text);
    lv_obj_invalidate(ui_speedlabel);  // Actualiser l'objet de l'humidité

    // Rafraîchir l'écran si nécessaire
    lv_refr_now(NULL);  // Rafraîchissement complet (optionnel)
}

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fondmontre2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_fondmontre2, 240);
    lv_obj_set_height(ui_fondmontre2, 240);
    lv_obj_set_x(ui_fondmontre2, 0);
    lv_obj_set_y(ui_fondmontre2, -1);
    lv_obj_set_align(ui_fondmontre2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fondmontre2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fondmontre2, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fondmontre2, lv_color_hex(0x3C3B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fondmontre2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedlogo = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_speedlogo, &ui_img_426965798);
    lv_obj_set_width(ui_speedlogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_speedlogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_speedlogo, -60);
    lv_obj_set_y(ui_speedlogo, -40);
    lv_obj_set_align(ui_speedlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speedlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_speedlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_magnlabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_magnlabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_magnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_magnlabel, 0);
    lv_obj_set_y(ui_magnlabel, 20);
    lv_obj_set_align(ui_magnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_magnlabel, "magn");
    lv_obj_set_style_text_color(ui_magnlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_magnlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_magnlabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedlabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_speedlabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_speedlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedlabel, 0);
    lv_obj_set_y(ui_speedlabel, -40);
    lv_obj_set_align(ui_speedlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedlabel, "speed");
    lv_obj_set_style_text_color(ui_speedlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedlabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextbutton2 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_nextbutton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1976085116, NULL);
    lv_obj_set_width(ui_nextbutton2, 32);
    lv_obj_set_height(ui_nextbutton2, 32);
    lv_obj_set_x(ui_nextbutton2, 0);
    lv_obj_set_y(ui_nextbutton2, 80);
    lv_obj_set_align(ui_nextbutton2, LV_ALIGN_CENTER);

    ui_Image1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image1, &ui_img_boussole_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, -60);
    lv_obj_set_y(ui_Image1, 20);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_nextbutton2, ui_event_nextbutton2, LV_EVENT_ALL, NULL);

}
