// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "../ui.h"

extern lv_obj_t *ui_templabel;
extern lv_obj_t *ui_humlabel;
extern lv_obj_t *ui_hourlabel;
extern lv_obj_t *ui_Minlabel;
extern lv_obj_t *ui_daylabel;
extern lv_obj_t *ui_monthlabel;
extern lv_obj_t *ui_yearlabel;
void update_display_time(int hour, int minute, int day, int month, int year) {
    char hour_text[10];
    char min_text[10];
    char day_text[5];
    char month_text[5];
    char year_text[5];

    // Formatage des valeurs
    snprintf(hour_text, sizeof(hour_text), "%02d", hour);
    snprintf(min_text, sizeof(min_text), "%02d", minute);
    snprintf(day_text, sizeof(day_text), "%02d", day);
    snprintf(month_text, sizeof(month_text), "%02d", month);
    snprintf(year_text, sizeof(year_text), "%02d", year % 100); // Affichage YY seulement

    // Mise à jour des labels LVGL
    lv_label_set_text(ui_hourlabel, hour_text);
    lv_obj_invalidate(ui_hourlabel);

    lv_label_set_text(ui_Minlabel, min_text);
    lv_obj_invalidate(ui_Minlabel);

    lv_label_set_text(ui_daylabel, day_text);
    lv_obj_invalidate(ui_daylabel);

    lv_label_set_text(ui_monthlabel, month_text);
    lv_obj_invalidate(ui_monthlabel);

    lv_label_set_text(ui_yearlabel, year_text);
    lv_obj_invalidate(ui_yearlabel);

    // Rafraîchissement complet (optionnel mais utile)
    lv_refr_now(NULL);
}


void update_display_hts221(double temp, double hum) {
    // Mise à jour de la température
    char temp_text[20];
    sprintf(temp_text, "%.1f°C", temp);  // Affichage avec une décimale
    lv_label_set_text(ui_templabel, temp_text);
    lv_obj_invalidate(ui_templabel);  // Actualiser l'objet de la température

    // Mise à jour de l'humidité
    char hum_text[20];
    sprintf(hum_text, "%.1f%%", hum);  // Affichage avec une décimale
    lv_label_set_text(ui_humlabel, hum_text);
    lv_obj_invalidate(ui_humlabel);  // Actualiser l'objet de l'humidité

    // Rafraîchir l'écran si nécessaire
    lv_refr_now(NULL);  // Rafraîchissement complet (optionnel)
}



void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fondmontre = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_fondmontre, 240);
    lv_obj_set_height(ui_fondmontre, 240);
    lv_obj_set_x(ui_fondmontre, 0);
    lv_obj_set_y(ui_fondmontre, -1);
    lv_obj_set_align(ui_fondmontre, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fondmontre, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fondmontre, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fondmontre, lv_color_hex(0x3C3B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fondmontre, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hourlabel, 80);
    lv_obj_set_height(ui_hourlabel, 49);
    lv_obj_set_x(ui_hourlabel, -50);
    lv_obj_set_y(ui_hourlabel, 0);
    lv_obj_set_align(ui_hourlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hourlabel, "HH");
    lv_obj_set_style_text_color(ui_hourlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hourlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_hourlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hourlabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_daylabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_daylabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_daylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_daylabel, -40);
    lv_obj_set_y(ui_daylabel, 40);
    lv_obj_set_align(ui_daylabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_daylabel, "29");
    lv_obj_set_style_text_color(ui_daylabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_daylabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_daylabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_templabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_templabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_templabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_templabel, -34);
    lv_obj_set_y(ui_templabel, -60);
    lv_obj_set_align(ui_templabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_templabel, "Temp");
    lv_obj_set_style_text_color(ui_templabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_templabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_templabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humlabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_humlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humlabel, 62);
    lv_obj_set_y(ui_humlabel, -60);
    lv_obj_set_align(ui_humlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humlabel, "Hum");
    lv_obj_set_style_text_color(ui_humlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humlabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humlogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_humlogo, &ui_img_humidite_png);
    lv_obj_set_width(ui_humlogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_humlogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_humlogo, 21);
    lv_obj_set_y(ui_humlogo, -61);
    lv_obj_set_align(ui_humlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humlogo, 255);

    ui_Minlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Minlabel, 80);
    lv_obj_set_height(ui_Minlabel, 49);
    lv_obj_set_x(ui_Minlabel, 50);
    lv_obj_set_y(ui_Minlabel, 0);
    lv_obj_set_align(ui_Minlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minlabel, "MM");
    lv_obj_set_style_text_color(ui_Minlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Minlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minlabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_twopoint = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_twopoint, 20);
    lv_obj_set_height(ui_twopoint, 49);
    lv_obj_set_align(ui_twopoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_twopoint, ":");
    lv_obj_set_style_text_color(ui_twopoint, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_twopoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_twopoint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_twopoint, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_templogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_templogo, &ui_img_temperature_png);
    lv_obj_set_width(ui_templogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_templogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_templogo, -75);
    lv_obj_set_y(ui_templogo, -61);
    lv_obj_set_align(ui_templogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_templogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_templogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_monthlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_monthlabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_monthlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_monthlabel, 0);
    lv_obj_set_y(ui_monthlabel, 40);
    lv_obj_set_align(ui_monthlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monthlabel, "02");
    lv_obj_set_style_text_color(ui_monthlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_monthlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_monthlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearlabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_yearlabel, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_yearlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearlabel, 40);
    lv_obj_set_y(ui_yearlabel, 40);
    lv_obj_set_align(ui_yearlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearlabel, "25");
    lv_obj_set_style_text_color(ui_yearlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yearlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yearlabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slash = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_slash, &ui_img_887419821);
    lv_obj_set_width(ui_slash, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_slash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slash, -20);
    lv_obj_set_y(ui_slash, 40);
    lv_obj_set_align(ui_slash, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_slash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_slash, 128);

    ui_slash1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_slash1, &ui_img_887419821);
    lv_obj_set_width(ui_slash1, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_slash1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slash1, 20);
    lv_obj_set_y(ui_slash1, 40);
    lv_obj_set_align(ui_slash1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_slash1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_slash1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_slash1, 128);

    ui_Nextbutton = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_Nextbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1976085116, NULL);
    lv_obj_set_width(ui_Nextbutton, 32);
    lv_obj_set_height(ui_Nextbutton, 32);
    lv_obj_set_x(ui_Nextbutton, 0);
    lv_obj_set_y(ui_Nextbutton, 80);
    lv_obj_set_align(ui_Nextbutton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Nextbutton, ui_event_Nextbutton, LV_EVENT_ALL, NULL);

}
