// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: interface_montre

#include "../ui.h"
extern lv_obj_t *ui_Minlabel1;
extern lv_obj_t *ui_Seclabel;

void update_display_chrono(int mm, int ss){
    char sec_text[10];
    char min_text[10];
    snprintf(sec_text, sizeof(sec_text), "%02d", ss);
    snprintf(min_text, sizeof(min_text), "%02d", mm);
    lv_label_set_text(ui_Minlabel1, min_text);
    lv_label_set_text(ui_Seclabel, sec_text);
    lv_refr_now(NULL);

}
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fondmontre1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_fondmontre1, 240);
    lv_obj_set_height(ui_fondmontre1, 240);
    lv_obj_set_x(ui_fondmontre1, 0);
    lv_obj_set_y(ui_fondmontre1, -1);
    lv_obj_set_align(ui_fondmontre1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fondmontre1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fondmontre1, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fondmontre1, lv_color_hex(0x3C3B74), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fondmontre1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_twopoint1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_twopoint1, 20);
    lv_obj_set_height(ui_twopoint1, 49);
    lv_obj_set_x(ui_twopoint1, 0);
    lv_obj_set_y(ui_twopoint1, -10);
    lv_obj_set_align(ui_twopoint1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_twopoint1, ":");
    lv_obj_set_style_text_color(ui_twopoint1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_twopoint1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_twopoint1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_twopoint1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minlabel1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Minlabel1, 80);
    lv_obj_set_height(ui_Minlabel1, 49);
    lv_obj_set_x(ui_Minlabel1, -50);
    lv_obj_set_y(ui_Minlabel1, -10);
    lv_obj_set_align(ui_Minlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minlabel1, "00");
    lv_obj_set_style_text_color(ui_Minlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Minlabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minlabel1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chronolabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Chronolabel, 131);
    lv_obj_set_height(ui_Chronolabel, 16);
    lv_obj_set_x(ui_Chronolabel, 0);
    lv_obj_set_y(ui_Chronolabel, -60);
    lv_obj_set_align(ui_Chronolabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Chronolabel, "Chronometre\n");
    lv_obj_set_style_text_color(ui_Chronolabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chronolabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chronolabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chronolabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextbutton1 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_nextbutton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1976085116, NULL);
    lv_obj_set_width(ui_nextbutton1, 32);
    lv_obj_set_height(ui_nextbutton1, 32);
    lv_obj_set_x(ui_nextbutton1, 0);
    lv_obj_set_y(ui_nextbutton1, 80);
    lv_obj_set_align(ui_nextbutton1, LV_ALIGN_CENTER);

    ui_stopbutton = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_stopbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_allumer_png, NULL);
    lv_obj_set_width(ui_stopbutton, 32);
    lv_obj_set_height(ui_stopbutton, 32);
    lv_obj_set_x(ui_stopbutton, 0);
    lv_obj_set_y(ui_stopbutton, 35);
    lv_obj_set_align(ui_stopbutton, LV_ALIGN_CENTER);

    ui_Seclabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Seclabel, 80);
    lv_obj_set_height(ui_Seclabel, 49);
    lv_obj_set_x(ui_Seclabel, 50);
    lv_obj_set_y(ui_Seclabel, -10);
    lv_obj_set_align(ui_Seclabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Seclabel, "00");
    lv_obj_set_style_text_color(ui_Seclabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Seclabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Seclabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Seclabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startbutton = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_startbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1869196203, NULL);
    lv_obj_set_width(ui_startbutton, 32);
    lv_obj_set_height(ui_startbutton, 32);
    lv_obj_set_x(ui_startbutton, -40);
    lv_obj_set_y(ui_startbutton, 35);
    lv_obj_set_align(ui_startbutton, LV_ALIGN_CENTER);

    ui_razbutton = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_razbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_poubelle_png, NULL);
    lv_obj_set_width(ui_razbutton, 32);
    lv_obj_set_height(ui_razbutton, 32);
    lv_obj_set_x(ui_razbutton, 40);
    lv_obj_set_y(ui_razbutton, 35);
    lv_obj_set_align(ui_razbutton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_nextbutton1, ui_event_nextbutton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopbutton, ui_event_stopbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startbutton, ui_event_startbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_razbutton, ui_event_razbutton, LV_EVENT_ALL, NULL);

}
